const KEY='ma-sante-v016';
const OLD_KEYS=['ma-sante-v015','ma-sante-v014','ma-sante-v013','ma-sante-v012','ma-sante-v011','ma-sante-v01'];
function uid(){return (globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function freshDefault(){return{schemaVersion:2,treatments:[{id:uid(),name:'XIGDUO XR',strength:'5 mg/1000 mg',unit:'comprimé',reason:'diabète sucré type 2',instruction:'Avant le repas',information:'',start:'2024-11-26',end:'',stock:82,expiry:'2027-03-31',photo:'',periodicity:'daily',weekdays:[],monthDays:[],schedule:[{time:'09:00',qty:1},{time:'19:00',qty:1}]}],pharmacy:[],takes:{},history:[]}}
function migrate(data){if(!data||!Array.isArray(data.treatments))data=freshDefault();data.schemaVersion=2;data.treatments=(data.treatments||[]).map(t=>({...t,information:t.information||'',periodicity:t.periodicity||'daily',weekdays:Array.isArray(t.weekdays)?t.weekdays:[],monthDays:Array.isArray(t.monthDays)?t.monthDays:[],schedule:Array.isArray(t.schedule)?t.schedule:[]}));data.pharmacy=Array.isArray(data.pharmacy)?data.pharmacy:[];data.takes=data.takes||{};Object.keys(data.takes).forEach(k=>{if(typeof data.takes[k]==='string')data.takes[k]={time:data.takes[k],qty:null,unit:'',actualDate:k.slice(0,10),note:''}});data.history=Array.isArray(data.history)?data.history:[];return data}
function load(){try{for(const k of [KEY,...OLD_KEYS]){const raw=localStorage.getItem(k);if(raw)return migrate(JSON.parse(raw))}return freshDefault()}catch(e){console.error(e);return freshDefault()}}
let db=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));renderAll();return true}catch(e){console.error(e);alert("Impossible d'enregistrer localement : "+(e.message||e));return false}}
function esc(x=''){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function isoDay(d=new Date()){let x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function currentTime(){return new Date().toLocaleTimeString('fr-CH',{hour:'2-digit',minute:'2-digit'})}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('fr-CH',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
function activeOn(t,date){return(!t.start||date>=t.start)&&(!t.end||date<=t.end)}
function appliesOn(t,dateStr){if(!activeOn(t,dateStr))return false;const d=new Date(dateStr+'T12:00:00'),p=t.periodicity||'daily';if(p==='daily')return true;if(p==='weekly')return(t.weekdays||[]).map(Number).includes(d.getDay());if(p==='monthly')return(t.monthDays||[]).map(Number).includes(d.getDate());return true}
function instructionPriority(text){const s=(text||'').toLowerCase();if(s.includes('à jeun'))return 0;if(s.includes('avant le repas'))return 1;if(s.includes('pendant le repas'))return 2;if(s.includes('après le repas'))return 3;return 4}
function periodicityLabel(t){const p=t.periodicity||'daily';if(p==='daily')return'Tous les jours';if(p==='weekly'){const n=['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'];return(t.weekdays||[]).map(x=>n[Number(x)]).join(', ')||'Jours non définis'}if(p==='monthly')return'Jour(s) '+(t.monthDays||[]).join(', ')+' du mois';return''}
function openModal(id){document.getElementById(id).classList.add('open')}
function closeModal(id){document.getElementById(id).classList.remove('open')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');renderAll()});

function getCatalog(kind){const vals=new Set();db.treatments.forEach(t=>{if(t[kind])vals.add(t[kind])});if(kind==='unit')db.pharmacy.forEach(p=>{if(p.unit)vals.add(p.unit)});return[...vals].filter(Boolean).sort((a,b)=>a.localeCompare(b,'fr'))}
function populateDynamicSelect(selectId,otherId,kind,current=''){const sel=document.getElementById(selectId),vals=getCatalog(kind);sel.innerHTML='<option value="">— Choisir —</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')+'<option value="__OTHER__">Autre…</option>';if(current&&vals.includes(current))sel.value=current;else if(current){sel.value='__OTHER__';document.getElementById(otherId).value=current}else sel.value='';syncOther(selectId,otherId)}
function syncOther(selectId,inputId){document.getElementById(inputId).classList.toggle('hidden',document.getElementById(selectId).value!=='__OTHER__')}
function selectedOrOther(selectId,inputId){const s=document.getElementById(selectId);return s.value==='__OTHER__'?document.getElementById(inputId).value.trim():s.value}

function renderToday(){const day=isoDay();document.getElementById('todayDate').textContent=fmtDate(day);let events=[];db.treatments.filter(t=>appliesOn(t,day)).forEach(t=>t.schedule.forEach(s=>events.push({t,s})));events.sort((a,b)=>a.s.time.localeCompare(b.s.time)||instructionPriority(a.t.instruction)-instructionPriority(b.t.instruction)||a.t.name.localeCompare(b.t.name,'fr'));let html='',last='';events.forEach(({t,s})=>{if(s.time!==last){if(last)html+=`<div class="actions" style="justify-content:flex-end;margin:3px 0 9px"><button class="secondary small" onclick="takeGroup('${day}','${last}')">Tout enregistrer ${last}</button></div>`;last=s.time;html+=`<div class="time-head"><div class="time">${s.time}</div></div>`}const k=`${day}|${t.id}|${s.time}`,done=db.takes[k],actual=done?(done.qty??s.qty):null;html+=`<div class="card compact-card dose-row ${done?'taken':''}"><div class="dose-main"><strong>${esc(t.name)} ${esc(t.strength||'')}</strong><div class="dose-sub">${s.qty} ${esc(t.unit)}${t.instruction?' · '+esc(t.instruction):''}${done?` · pris: ${actual} ${esc(done.unit||t.unit)} à ${esc(done.time||'')}`:''}</div></div><div class="actions"><button class="${done?'secondary':'primary'} icon-btn" onclick="${done?`cancelTake('${t.id}','${s.time}')`:`openTake('${t.id}','${s.time}')`}">${done?'Annuler':'Pris'}</button></div></div>`});if(last)html+=`<div class="actions" style="justify-content:flex-end;margin:3px 0 9px"><button class="secondary small" onclick="takeGroup('${day}','${last}')">Tout enregistrer ${last}</button></div>`;document.getElementById('todayList').innerHTML=html||'<div class="card">Aucune prise planifiée aujourd’hui.</div>';renderTodayHistory()}
function renderTodayHistory(){const day=isoDay(),items=db.history.filter(h=>h.date===day).sort((a,b)=>(b.time||'').localeCompare(a.time||''));document.getElementById('todayHistoryCount').textContent=items.length;document.getElementById('todayHistory').innerHTML=items.length?items.map(h=>`<div class="history-row"><div><strong>${esc(h.time||'')}</strong><br><span class="badge">${h.kind==='prn'?'Au besoin':'Planifié'}</span></div><div><strong>${esc(h.name)}</strong> ${esc(h.strength||'')}<div class="muted">${h.qty} ${esc(h.unit||'')}${h.note?' · '+esc(h.note):''}</div></div><div></div></div>`).join(''):'<div class="muted" style="padding-top:7px">Aucune prise enregistrée aujourd’hui.</div>'}
function openTake(id,time){const t=db.treatments.find(x=>x.id===id),s=t?.schedule.find(x=>x.time===time);if(!t||!s)return;const day=isoDay(),k=`${day}|${id}|${time}`,existing=db.takes[k];document.getElementById('takeTreatmentId').value=id;document.getElementById('takePlannedTime').value=time;document.getElementById('takeModalTitle').textContent=`${t.name} ${t.strength||''}`;document.getElementById('takeQty').value=existing?.qty??s.qty;document.getElementById('takeUnit').value=t.unit||'';document.getElementById('takeDate').value=existing?.actualDate||day;document.getElementById('takeTime').value=existing?.time||currentTime();document.getElementById('takeNote').value=existing?.note||'';openModal('takeModal')}
document.getElementById('confirmTake').onclick=()=>{const id=document.getElementById('takeTreatmentId').value,time=document.getElementById('takePlannedTime').value,t=db.treatments.find(x=>x.id===id);if(!t)return;const day=isoDay(),k=`${day}|${id}|${time}`,old=db.takes[k],qty=Number(document.getElementById('takeQty').value||0),actualDate=document.getElementById('takeDate').value,actualTime=document.getElementById('takeTime').value;if(qty<=0)return alert('Indique la quantité réellement prise.');if(old?.qty)t.stock=Number(t.stock||0)+Number(old.qty);t.stock=Math.max(0,Number(t.stock||0)-qty);db.takes[k]={qty,unit:t.unit,actualDate,time:actualTime,note:document.getElementById('takeNote').value.trim()};db.history=db.history.filter(h=>h.eventKey!==k);db.history.push({id:uid(),eventKey:k,kind:'planned',date:actualDate,time:actualTime,name:t.name,strength:t.strength,qty,unit:t.unit,note:document.getElementById('takeNote').value.trim()});closeModal('takeModal');save()}
function cancelTake(id,time){const day=isoDay(),k=`${day}|${id}|${time}`,old=db.takes[k],t=db.treatments.find(x=>x.id===id);if(old?.qty&&t)t.stock=Number(t.stock||0)+Number(old.qty);delete db.takes[k];db.history=db.history.filter(h=>h.eventKey!==k);save()}
function takeGroup(day,time){const list=[];db.treatments.filter(t=>appliesOn(t,day)).forEach(t=>t.schedule.filter(s=>s.time===time).forEach(s=>list.push({t,s})));list.forEach(({t,s})=>{const k=`${day}|${t.id}|${time}`;if(db.takes[k])return;const qty=Number(s.qty||0);t.stock=Math.max(0,Number(t.stock||0)-qty);const tm=currentTime();db.takes[k]={qty,unit:t.unit,actualDate:day,time:tm,note:''};db.history.push({id:uid(),eventKey:k,kind:'planned',date:day,time:tm,name:t.name,strength:t.strength,qty,unit:t.unit,note:''})});save()}

document.getElementById('prnBtn').onclick=()=>{const list=db.pharmacy.filter(p=>Number(p.stock||0)>0);document.getElementById('prnChoiceList').innerHTML=list.length?list.map(p=>`<button class="secondary choice" onclick="choosePrn('${p.id}')"><strong>${esc(p.name)} ${esc(p.strength||'')}</strong><br><span class="muted">Stock: ${p.stock} ${esc(p.unit||'')}</span></button>`).join(''):'<div class="notice">Aucun produit disponible dans Ma pharmacie. Ajoute d’abord le médicament dans l’onglet Pharmacie.</div>';openModal('prnChoiceModal')}
function choosePrn(id){const p=db.pharmacy.find(x=>x.id===id);if(!p)return;closeModal('prnChoiceModal');document.getElementById('prnPharmacyId').value=id;document.getElementById('prnTakeTitle').textContent=`${p.name} ${p.strength||''}`;document.getElementById('prnQty').value=1;document.getElementById('prnUnit').value=p.unit||'';document.getElementById('prnDate').value=isoDay();document.getElementById('prnTime').value=currentTime();document.getElementById('prnNote').value='';openModal('prnTakeModal')}
document.getElementById('confirmPrn').onclick=()=>{const p=db.pharmacy.find(x=>x.id===document.getElementById('prnPharmacyId').value);if(!p)return;const qty=Number(document.getElementById('prnQty').value||0);if(qty<=0)return alert('Indique la quantité prise.');if(qty>Number(p.stock||0)&&!confirm('La quantité dépasse le stock enregistré. Continuer ?'))return;p.stock=Math.max(0,Number(p.stock||0)-qty);db.history.push({id:uid(),eventKey:'prn-'+uid(),kind:'prn',date:document.getElementById('prnDate').value,time:document.getElementById('prnTime').value,name:p.name,strength:p.strength,qty,unit:p.unit,note:document.getElementById('prnNote').value.trim(),pharmacyId:p.id});closeModal('prnTakeModal');save()}

function renderTreatments(){document.getElementById('treatmentList').innerHTML=db.treatments.length?db.treatments.map(t=>`<div class="card compact-card treatment-row"><div class="treatment-main"><strong>${esc(t.name)} ${esc(t.strength||'')}</strong><div class="muted">${t.schedule.map(s=>`${s.time} ${s.qty} ${esc(t.unit)}`).join(' · ')} · ${esc(periodicityLabel(t))}${t.instruction?' · '+esc(t.instruction):''}</div>${t.information?`<div class="info-note">${esc(t.information)}</div>`:''}</div><div class="actions"><button class="secondary icon-btn" onclick="editTreatment('${t.id}')">Modifier</button><button class="danger icon-btn" onclick="deleteTreatment('${t.id}')">×</button></div></div>`).join(''):'<div class="card">Aucun traitement.</div>'}
function addScheduleRow(time='09:00',qty=1){const d=document.createElement('div');d.className='schedule-row';d.innerHTML=`<input type="time" class="stime" value="${time}"><input type="number" class="sqty" min="0" step=".5" value="${qty}"><button class="danger" type="button">Retirer</button>`;d.querySelector('button').onclick=()=>d.remove();document.getElementById('scheduleRows').appendChild(d)}
document.getElementById('addSchedule').onclick=()=>addScheduleRow('12:00',1)
function updatePeriodUI(){const p=document.getElementById('periodicity').value;document.getElementById('weeklyOptions').classList.toggle('hidden',p!=='weekly');document.getElementById('monthlyOptions').classList.toggle('hidden',p!=='monthly')}
document.getElementById('periodicity').onchange=updatePeriodUI;['unit','reason','instruction'].forEach(id=>document.getElementById(id).onchange=()=>syncOther(id,id+'Other'))
function resetTreatmentForm(){document.getElementById('editId').value='';document.getElementById('formTitle').textContent='Ajouter un traitement';['name','strength','unitOther','reasonOther','instructionOther','information','end','expiry','monthDays'].forEach(id=>document.getElementById(id).value='');document.getElementById('start').value=isoDay();document.getElementById('stock').value=0;document.getElementById('photo').value='';document.getElementById('periodicity').value='daily';document.querySelectorAll('.weekday').forEach(c=>c.checked=false);document.getElementById('scheduleRows').innerHTML='';addScheduleRow('09:00',1);updatePeriodUI();populateDynamicSelect('unit','unitOther','unit');populateDynamicSelect('reason','reasonOther','reason');populateDynamicSelect('instruction','instructionOther','instruction')}
document.getElementById('openTreatmentForm').onclick=()=>{resetTreatmentForm();document.getElementById('treatmentFormPanel').classList.add('open');document.getElementById('treatmentFormPanel').scrollIntoView({behavior:'smooth',block:'start'})};document.getElementById('cancelEdit').onclick=()=>{resetTreatmentForm();document.getElementById('treatmentFormPanel').classList.remove('open')}
function fileToDataURL(file){return new Promise((res,rej)=>{if(!file)return res('');const reader=new FileReader();reader.onerror=rej;reader.onload=()=>{const img=new Image();img.onerror=rej;img.onload=()=>{const max=800;let w=img.width,h=img.height;if(w>max||h>max){const sc=Math.min(max/w,max/h);w=Math.round(w*sc);h=Math.round(h*sc)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);res(canvas.toDataURL('image/jpeg',.72))};img.src=reader.result};reader.readAsDataURL(file)})}
document.getElementById('saveTreatment').onclick=async()=>{try{const el=id=>document.getElementById(id);if(!el('name').value.trim())return alert('Indique le nom du médicament.');const currentId=el('editId').value,previous=db.treatments.find(t=>t.id===currentId);let pic=previous?.photo||'';if(el('photo').files[0])pic=await fileToDataURL(el('photo').files[0]);const schedule=[...el('scheduleRows').children].map(r=>({time:r.querySelector('.stime').value,qty:Number(r.querySelector('.sqty').value||0)})).filter(x=>x.time);if(!schedule.length)return alert('Ajoute au moins une heure de prise.');const periodicity=el('periodicity').value,weekdays=[...document.querySelectorAll('.weekday:checked')].map(c=>Number(c.value)),monthDays=el('monthDays').value.split(',').map(x=>Number(x.trim())).filter(x=>x>=1&&x<=31);if(periodicity==='weekly'&&!weekdays.length)return alert('Choisis au moins un jour de la semaine.');if(periodicity==='monthly'&&!monthDays.length)return alert('Indique au moins un jour du mois.');const t={id:currentId||uid(),name:el('name').value.trim(),strength:el('strength').value.trim(),unit:selectedOrOther('unit','unitOther')||'unité',reason:selectedOrOther('reason','reasonOther'),instruction:selectedOrOther('instruction','instructionOther'),information:el('information').value.trim(),start:el('start').value,end:el('end').value,stock:Number(el('stock').value||0),expiry:el('expiry').value,photo:pic,periodicity,weekdays,monthDays,schedule};if(previous)db.treatments[db.treatments.findIndex(x=>x.id===t.id)]=t;else db.treatments.push(t);if(save()){resetTreatmentForm();el('treatmentFormPanel').classList.remove('open');el('treatmentList').scrollIntoView({behavior:'smooth',block:'start'})}}catch(e){console.error(e);alert('Erreur pendant l’enregistrement : '+(e.message||e))}}
function editTreatment(id){const t=db.treatments.find(x=>x.id===id);if(!t)return;const el=x=>document.getElementById(x);el('treatmentFormPanel').classList.add('open');el('editId').value=t.id;el('formTitle').textContent='Modifier le traitement';el('name').value=t.name||'';el('strength').value=t.strength||'';populateDynamicSelect('unit','unitOther','unit',t.unit||'');populateDynamicSelect('reason','reasonOther','reason',t.reason||'');populateDynamicSelect('instruction','instructionOther','instruction',t.instruction||'');el('information').value=t.information||'';el('start').value=t.start||'';el('end').value=t.end||'';el('stock').value=t.stock??0;el('expiry').value=t.expiry||'';el('periodicity').value=t.periodicity||'daily';document.querySelectorAll('.weekday').forEach(c=>c.checked=(t.weekdays||[]).map(Number).includes(Number(c.value)));el('monthDays').value=(t.monthDays||[]).join(',');updatePeriodUI();el('scheduleRows').innerHTML='';(t.schedule||[]).forEach(s=>addScheduleRow(s.time,s.qty));if(!t.schedule?.length)addScheduleRow('09:00',1);el('treatmentFormPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function deleteTreatment(id){if(confirm('Supprimer ce traitement ?')){db.treatments=db.treatments.filter(x=>x.id!==id);save()}}

function nextMonday(){let d=new Date(),day=d.getDay(),delta=(8-day)%7;if(delta===0)delta=7;d.setDate(d.getDate()+delta);return isoDay(d)}
document.getElementById('weekStart').value=nextMonday();document.getElementById('generateWeek').onclick=()=>{const start=document.getElementById('weekStart').value;if(!start)return;const dates=[];for(let i=0;i<7;i++){let d=new Date(start+'T12:00:00');d.setDate(d.getDate()+i);dates.push(isoDay(d))}let html='<div class="notice"><strong>Préparation par médicament.</strong> La photo aide à identifier la boîte. Une dose préparée n’est pas encore une dose consommée.</div>';db.treatments.forEach(t=>{let uses=[];dates.forEach(d=>{if(appliesOn(t,d))t.schedule.forEach(s=>uses.push({d,time:s.time,qty:s.qty}))});if(!uses.length)return;let total=uses.reduce((a,x)=>a+x.qty,0);html+=`<div class="card">${t.photo?`<img class="photo" src="${t.photo}">`:''}<div class="title-row slim"><h3>${esc(t.name)} ${esc(t.strength||'')}</h3><span class="badge">${total} ${esc(t.unit)} à préparer</span></div><div class="week"><table><tr><th>Jour</th><th>À placer</th></tr>${dates.map(d=>{let u=uses.filter(x=>x.d===d);return`<tr><td>${new Date(d+'T12:00').toLocaleDateString('fr-CH',{weekday:'short',day:'2-digit',month:'2-digit'})}</td><td>${u.length?u.map(x=>`${x.time}: ${x.qty} ${esc(t.unit)}`).join('<br>'):'—'}</td></tr>`}).join('')}</table></div></div>`});document.getElementById('weekPlan').innerHTML=html||'<div class="card">Aucun traitement actif pour cette semaine.</div>'}

function renderPharmacy(){populateDynamicSelect('phUnit','phUnitOther','unit');document.getElementById('pharmacyList').innerHTML=db.pharmacy.length?db.pharmacy.map(p=>`<div class="card compact-card pharmacy-row"><div class="pharmacy-main">${p.photo?`<img class="photo" src="${p.photo}">`:''}<strong>${esc(p.name)} ${esc(p.strength||'')}</strong><div class="muted">Stock: ${p.stock} ${esc(p.unit||'')}${p.expiry?' · péremption '+esc(p.expiry):''}</div>${p.information?`<div class="info-note">${esc(p.information)}</div>`:''}</div><div class="actions"><button class="secondary icon-btn" onclick="editPharmacy('${p.id}')">Modifier</button><button class="danger icon-btn" onclick="deletePharmacy('${p.id}')">×</button></div></div>`).join(''):'<div class="card">Aucun produit enregistré dans la pharmacie.</div>'}
function resetPharmacyForm(){['pharmacyEditId','phName','phStrength','phUnitOther','phExpiry','phInformation'].forEach(id=>document.getElementById(id).value='');document.getElementById('phStock').value=0;document.getElementById('phPhoto').value='';document.getElementById('pharmacyFormTitle').textContent='Ajouter à la pharmacie';populateDynamicSelect('phUnit','phUnitOther','unit')}
document.getElementById('phUnit').onchange=()=>syncOther('phUnit','phUnitOther');document.getElementById('openPharmacyForm').onclick=()=>{resetPharmacyForm();document.getElementById('pharmacyFormPanel').classList.add('open');document.getElementById('pharmacyFormPanel').scrollIntoView({behavior:'smooth'})};document.getElementById('cancelPharmacy').onclick=()=>{resetPharmacyForm();document.getElementById('pharmacyFormPanel').classList.remove('open')}
document.getElementById('savePharmacy').onclick=async()=>{const el=id=>document.getElementById(id);if(!el('phName').value.trim())return alert('Indique le nom du produit.');const id=el('pharmacyEditId').value,old=db.pharmacy.find(p=>p.id===id);let pic=old?.photo||'';if(el('phPhoto').files[0])pic=await fileToDataURL(el('phPhoto').files[0]);const p={id:id||uid(),name:el('phName').value.trim(),strength:el('phStrength').value.trim(),unit:selectedOrOther('phUnit','phUnitOther')||'unité',stock:Number(el('phStock').value||0),expiry:el('phExpiry').value,information:el('phInformation').value.trim(),photo:pic};if(old)db.pharmacy[db.pharmacy.findIndex(x=>x.id===p.id)]=p;else db.pharmacy.push(p);if(save()){resetPharmacyForm();el('pharmacyFormPanel').classList.remove('open')}}
function editPharmacy(id){const p=db.pharmacy.find(x=>x.id===id);if(!p)return;const el=x=>document.getElementById(x);el('pharmacyFormPanel').classList.add('open');el('pharmacyEditId').value=p.id;el('pharmacyFormTitle').textContent='Modifier le produit';el('phName').value=p.name||'';el('phStrength').value=p.strength||'';populateDynamicSelect('phUnit','phUnitOther','unit',p.unit||'');el('phStock').value=p.stock??0;el('phExpiry').value=p.expiry||'';el('phInformation').value=p.information||'';el('pharmacyFormPanel').scrollIntoView({behavior:'smooth'})}
function deletePharmacy(id){if(confirm('Supprimer ce produit de la pharmacie ?')){db.pharmacy=db.pharmacy.filter(x=>x.id!==id);save()}}

function renderFullHistory(){const items=[...db.history].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));document.getElementById('fullHistory').innerHTML=items.length?items.map(h=>`<div class="history-row"><div>${esc(h.date)}<br><strong>${esc(h.time||'')}</strong></div><div><strong>${esc(h.name)}</strong> ${esc(h.strength||'')}<div class="muted">${h.qty} ${esc(h.unit||'')} · ${h.kind==='prn'?'au besoin':'planifié'}${h.note?' · '+esc(h.note):''}</div></div><div></div></div>`).join(''):'<div class="muted">Historique vide.</div>'}
function renderAll(){renderTreatments();renderToday();renderPharmacy();renderFullHistory()}
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({app:'Ma Santé',version:'0.1.6',exportedAt:new Date().toISOString(),data:db},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ma-sante-backup-${isoDay()}.json`;a.click();URL.revokeObjectURL(a.href)}
document.getElementById('importFile').onchange=async e=>{try{const obj=JSON.parse(await e.target.files[0].text()),incoming=migrate(obj.data||obj);if(confirm('Remplacer les données locales par cette sauvegarde ?')){db=incoming;save();alert('Import terminé.')}}catch(err){alert('Fichier de sauvegarde non reconnu.')}}
resetTreatmentForm();resetPharmacyForm();renderAll();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(err=>console.warn('Service worker',err)));
